- type: replace
  path: /name
  value: postfix-production

- type: replace
  path: /stemcells/alias=default/name
  value: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

- type: replace
  path: /instance_groups/name=postfix/vm_type?
  value: smtp-small

- type: replace
  path: /instance_groups/name=postfix/azs
  value: [z1]

- type: replace
  path: /instance_groups/name=postfix/networks
  value:
  - name: smtp-private
    static_ips: ((terraform_outputs.production_smtp_private_ip))

- type: replace
  path: /variables/name=postfix_ssl/options/common_name
  value: ((terraform_outputs.production_smtp_private_ip))

- type: replace
  path: /variables/name=postfix_ssl/options/alternative_names
  value:
  - ((terraform_outputs.production_smtp_private_ip))

- type: replace
  path: /instance_groups/name=postfix/jobs/release=postfix/properties/postfix/sasl_users?/cloudgov
  value: ((cloudgov_pw))
